### ISSUE TITLE
Include the plural form of nouns in search

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#117]
There are certain words, where kids would search for the plural form (which would not show up).
For example "Kinder" would not show "Kind".
It would be great if the search could include the plural form of nouns.

**Comment by wintermeyer** [comment]
We'd have to add a second cologne phonetics entry for the plural too for this to work.

**Comment by wintermeyer** [comment]
> Might be a different issue: do we also want that for adjectives? For comparative and superlative?

Good thinking!

**Comment by wintermeyer** [comment]
@phylor It depends on the workload for this. My main problems for this: a) Budget and b) Time. I don't want to let this become a rabbit hole. See my email.

**Comment by phylor** [comment]
> @phylor It depends on the workload for this. My main problems for this: a) Budget and b) Time. I don't want to let this become a rabbit hole. See my email.

:+1: I'm thinking about a general solution for this.

At the moment `Word#cologne_phonetics` is a string. Let's say we change that to be an array. Every word could then add as many phonetic representations as it wants to. If any one of those matches, the word would be in the search results. Because Postgres has first-class support for arrays, this shouldn't degrade performance.

I'm unsure though if we should modify the existing `Word#cologne_phonetics` or if we need to add a new `Word#search_terms`. Do we need to know which of the phonetic representations is the singular form (e.g. `Kind`)? If we change it to an array (`[462, 4627]`), we technically don't know which representation is the singular and which one is the plural form.

We can of course always encode the word again and then we know which is which. I'm just feeling unsure about it. @wintermeyer What do you think? Does it make sense to add another `Word#search_terms` or shall we just change the existing `Word#cologne_phonetics` to become an array?

**Comment by cabotine** [comment]
Having the array would also help with irregular verbs (sein: bin, bist, ist, sind usw.).

**Comment by wintermeyer** [comment]
> At the moment `Word#cologne_phonetics` is a string. Let's say we change that to be an array.

I am a big fan of clean database structures and have never been a fan of using arrays in string fields. But if that is the easiest way to do it and PostgreSQL doesn't give us a penalty for it I am ok with that.

But please don't only think about phonetic search. If a user searches for Kinder instead of Kind we don't need phonetic results. We have to cover both ways.

> We can of course always encode the word again and then we know which is which. I'm just feeling unsure about it. @wintermeyer What do you think? Does it make sense to add another `Word#search_terms` or shall we just change the existing `Word#cologne_phonetics` to become an array?

I am not 100% sure if I understand what you are asking. If we go the array way we need one table field for phonetics and one for regular search. If we have match in regular we are golden. Phonetics is just the cherry on the cake.

**Comment by cabotine** [comment]
Should we create a new issue for (irregular) verbs ("sind" is a realistic search scenario) and comparative and superlative of adjectives (gut, besser, am besten is a realistic search scenario)?

**Comment by wintermeyer** [comment]
> Should we create a new issue for (irregular) verbs ("sind" is a realistic search scenario) and comparative and superlative of adjectives (gut, besser, am besten is a realistic search scenario)?

Please create a new issue with examples and the URLs those examples should lead to.

Implementing the search is possible. Making the search result meaningful is tricky. Right now I can search for "Kinder" but don't get GUI feedback that "Kind" is the result I am searching for.  CC @xamiam

**Comment by phylor** [comment]
> Should we create a new issue for (irregular) verbs ("sind" is a realistic search scenario) and comparative and superlative of adjectives (gut, besser, am besten is a realistic search scenario)?

Comparative/superlative of adjectives are already included. If you search for `besser`, you should find the adjective `gut`.

Verbs are not yet added. We have `Imperativ Singular`, `Imperativ Plural`, `Partizip 1`, `Partizip 2` and conjugations in present and past. Which ones would you want to search in (maybe create a new issue for that)?
