### ISSUE TITLE
Include Open Graph protocol in the HTML header

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#4]
I just share the link of the Zebra with a friend on WhatsApp and I realized it would be great to have the image set as a preview image.

Preview image for WhatsApp
<meta property="og:image" content="//cdn.example.com/uploads/images/webpage_300x200.png" />

Like described here:
https://ogp.me/
https://stackoverflow.com/questions/19778620/provide-an-image-for-whatsapp-link-sharing

**Comment by wintermeyer** [comment]
I like the idea.

@phylor Please send me an estimation for this by email. Isn't there a nifty Rails gem for this?

**Comment by phylor** [comment]
> @phylor Please send me an estimation for this by email. Isn't there a nifty Rails gem for this?

Haven't heard of a gem, but that certainly would be a good idea. It's usually easy enough to write out the tags in a partial.

**Comment by wintermeyer** [comment]
https://github.com/kpumuk/meta-tags#open-graph seems to be an easy way to include Open Graph.

**Comment by wintermeyer** [comment]
> Haven't heard of a gem, but that certainly would be a good idea. It's usually easy enough to write out the tags in a partial.

You are right about the easiness about using a partial for this. But if https://github.com/kpumuk/meta-tags#open-graph is a good solution for this too I'd prefer it. Simply because of future coders for this project who might not be so familiar with things and how probably would be able to do more "magic" with a tool set like meta-tags.

BTW: I know this is going to be a foot gun for me. Probably one of those gems which gets abandoned and that will create so much work for us down the road. It is always a gem which one could have solved by a couple of lines code. ;-)

**Comment by phylor** [comment]
I agree, let's use the gem. But even if the gem gets abandoned, it's easy and fast to re-implement. The gem hopefully does manage corner cases better than a quick implementation though.
