### ISSUE TITLE
Two step workflow for new themes

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#51]
While trying to create a new theme I'll get this validation error.

<img width="1280" alt="Bildschirm­foto 2022-11-14 um 08 52 49" src="https://user-images.githubusercontent.com/69770/201604759-28e2c3c7-72bc-42d3-bf7e-1e213c2d17e2.png">

## Todos

* [x] Increase size of template text area
* [x] Two step process
  * First ask for the word type
  * Display a form which is prepopulated with the default for that word type.

**Comment by wintermeyer** [comment]
Ahhh... I think I am missing a point here. Is it possible that this field should be bigger and populated with a default?

**Comment by phylor** [comment]
> Ahhh... I think I am missing a point here. Is it possible that this field should be bigger and populated with a default?

Yes, we can definitely make it bigger.

Prepopulating might be difficult regarding UX, because the default content depends on the selected word type. We could use the "noun" default template, but I'm unsure if people will understand that they need to change the template if they change the word type.

At the moment I hope that they start the form at the top. They first select the word type and then they might click on "Mit Standard-Template ersetzen" to populate it with a starter template.

We could also add a liquid comment in the field, or set a placeholder.

What do you prefer?

**Comment by wintermeyer** [comment]
> Yes, we can definitely make it bigger.

Please! One line is a bit small.

We even could discuss using some "big" JavaScript editor here. But I leave that open for future feature requests.

> Prepopulating might be difficult regarding UX, because the default content depends on the selected word type. We could use the "noun" default template, but I'm unsure if people will understand that they need to change the template if they change the word type.

WE NEED some sort of default content. But I see your point with the selected word type. The solution might be a two step workflow. Select a word type first, hit enter and than get a form with all the other fields.

> At the moment I hope that they start the form at the top. They first select the word type and then they might click on "Mit Standard-Template ersetzen" to populate it with a starter template.

Ahhhh!!! I saw the text but wasn't aware that it was a link and wasn't aware that it would populate the text field with the default content. If I don't get it many other users will not get it either. Let's try the two step workflow.

- First ask for the word type
- Display a form which is prepopulated with the default for that word type.
